apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
spec:
  selector:
    matchLabels:
      app: property-service
  replicas: 1
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
        - name: property-service
          image: registry.digitalocean.com/axelrodvl/property-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080