package co.axelrod.bookingservice.state;

public enum Events {
    CANCEL_BY_CUSTOMER, // CREATED -> CANCELED
    CONFIRM_BOOKING, // CREATED -> CONFIRMED
    DECLINE_BY_HOST, // CREATED -> DECLINED
    PAY_BY_CUSTOMER, // CONFIRMED -> PAID, CONFIRMED -> PAYMENT_FAILURE
    CANCEL_BY_PAYMENT_FAILURE, // PAYMENT_FAILURE -> CANCELED
    PAY_BY_CUSTOMER_AFTER_FAILURE, // PAYMENT_FAILURE -> PAID
    START_BOOKING, // PAID -> STARTED
    COMPLETE_BOOKING // STARTED -> COMPLETED
}
