kind: ConfigMap
apiVersion: v1
metadata:
  name: property-service
data:
  application.yml: |-
    spring:
      r2dbc:
        url: r2dbc:postgresql://postgresql.default.svc.cluster.local:5432/booking
        username: postgres
        password: postgres
      liquibase:
        url: jdbc:postgresql://postgresql.default.svc.cluster.local:5432/booking
        user: postgres
        password: postgres
        change-log: classpath:db/changelog/db.changelog-master.yml