# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "postgres"
  username: "postgres"
  password: "postgres"
  database: "booking"

# The postgres helm chart deployment will be using PVC postgresql-pv-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-pv-claim"

volumePermissions:
  enabled: true
